[package]
name = "nxp-hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
pac = {path = "../pac"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
