[package]
name = "pac"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = {version = "0.7.3", optional = true, features = ["device"]}
critical-section = { version = "1.1.3", optional = true }
vcell = "0.1.3"

[features]
rt = ["cortex-m-rt/device"]
